"""Long-lived model services and Attempt-scoped inference routing."""

from ascend_maze.inference.catalog import ModelCatalog
from ascend_maze.inference.client import chat, get_route_context
from ascend_maze.inference.contracts import (
    AttemptInferenceSummary,
    ChatRequest,
    ChatResponse,
    EngineMetrics,
    EngineProbe,
    InferenceCallError,
    InferenceEngineAdapter,
    InferenceRequestRecord,
    ModelControlEvent,
    ModelDemand,
    ModelInstance,
    ModelInstanceState,
    ModelRouteAcquireResult,
    ModelRouteContext,
    ModelRouteLeaseSnapshot,
    ModelRouteLeaseStatus,
    ModelSpec,
    PortLease,
    PortLeaseManager,
    ServiceHandle,
    ServiceLaunchRequest,
    ServiceProcessBackend,
    ServiceProcessExit,
    ServiceProcessProbe,
    ServiceStopResult,
    WarmupResult,
)
from ascend_maze.inference.coordinator import InferenceCoordinator
from ascend_maze.inference.instance_manager import ModelInstanceRecoveryRecord
from ascend_maze.inference.ports import InMemoryPortLeaseManager

__all__ = [
    "AttemptInferenceSummary",
    "ChatRequest",
    "ChatResponse",
    "EngineMetrics",
    "EngineProbe",
    "InferenceCallError",
    "InferenceCoordinator",
    "InferenceEngineAdapter",
    "InMemoryPortLeaseManager",
    "InferenceRequestRecord",
    "ModelCatalog",
    "ModelControlEvent",
    "ModelDemand",
    "ModelInstance",
    "ModelInstanceState",
    "ModelInstanceRecoveryRecord",
    "ModelRouteAcquireResult",
    "ModelRouteContext",
    "ModelRouteLeaseSnapshot",
    "ModelRouteLeaseStatus",
    "ModelSpec",
    "PortLease",
    "PortLeaseManager",
    "ServiceHandle",
    "ServiceLaunchRequest",
    "ServiceProcessBackend",
    "ServiceProcessExit",
    "ServiceProcessProbe",
    "ServiceStopResult",
    "WarmupResult",
    "chat",
    "get_route_context",
]
