# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ascend_maze.control.proto import control_pb2 as ascend__maze_dot_control_dot_proto_dot_control__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ascend_maze/control/proto/control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBootstrap = channel.unary_unary(
                '/ascend_maze.control.v1.NodeControl/GetBootstrap',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeBootstrapRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeBootstrapResponse.FromString,
                _registered_method=True)
        self.Connect = channel.stream_stream(
                '/ascend_maze.control.v1.NodeControl/Connect',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.AgentStreamMessage.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControllerStreamMessage.FromString,
                _registered_method=True)


class NodeControlServicer:
    """Missing associated documentation comment in .proto file."""

    def GetBootstrap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Connect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBootstrap,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeBootstrapRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeBootstrapResponse.SerializeToString,
            ),
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.AgentStreamMessage.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControllerStreamMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascend_maze.control.v1.NodeControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascend_maze.control.v1.NodeControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.NodeControl/GetBootstrap',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeBootstrapRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeBootstrapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ascend_maze.control.v1.NodeControl/Connect',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.AgentStreamMessage.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControllerStreamMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WorkerEventSinkStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Report = channel.unary_unary(
                '/ascend_maze.control.v1.WorkerEventSink/Report',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WorkerEventRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WorkerEventAck.FromString,
                _registered_method=True)
        self.OpenRunRecording = channel.unary_unary(
                '/ascend_maze.control.v1.WorkerEventSink/OpenRunRecording',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.OpenRunRecordingRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RecorderControlAck.FromString,
                _registered_method=True)
        self.FlushRunRecording = channel.unary_unary(
                '/ascend_maze.control.v1.WorkerEventSink/FlushRunRecording',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.FlushRunRecordingRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.FlushResultMessage.FromString,
                _registered_method=True)


class WorkerEventSinkServicer:
    """Missing associated documentation comment in .proto file."""

    def Report(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenRunRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushRunRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerEventSinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Report': grpc.unary_unary_rpc_method_handler(
                    servicer.Report,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WorkerEventRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WorkerEventAck.SerializeToString,
            ),
            'OpenRunRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenRunRecording,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.OpenRunRecordingRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RecorderControlAck.SerializeToString,
            ),
            'FlushRunRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushRunRecording,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.FlushRunRecordingRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.FlushResultMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascend_maze.control.v1.WorkerEventSink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascend_maze.control.v1.WorkerEventSink', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WorkerEventSink:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Report(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.WorkerEventSink/Report',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.WorkerEventRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.WorkerEventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenRunRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.WorkerEventSink/OpenRunRecording',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.OpenRunRecordingRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.RecorderControlAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushRunRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.WorkerEventSink/FlushRunRecording',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.FlushRunRecordingRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.FlushResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LocalControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetVersion = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetVersion',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetControllerStatus = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetControllerStatus',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.GetControllerStatusRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.GetControllerStatusResponse.FromString,
                _registered_method=True)
        self.GetSystemSnapshot = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetSystemSnapshot',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.SubmitWorkflow = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/SubmitWorkflow',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.SubmitWorkflowRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetSubmission = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetSubmission',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetClusterSnapshot = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetClusterSnapshot',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.WatchCluster = channel.unary_stream(
                '/ascend_maze.control.v1.LocalControl/WatchCluster',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WatchClusterRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetWorkerPools = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetWorkerPools',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.ListRuns = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/ListRuns',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetRun',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.WatchRun = channel.unary_stream(
                '/ascend_maze.control.v1.LocalControl/WatchRun',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WatchRunRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetRunEvents = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetRunEvents',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.GetRunEventsRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/CancelRun',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.DestroyRun = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/DestroyRun',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetTaskResultHandles = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetTaskResultHandles',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetModelCatalog = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetModelCatalog',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetModelInstances = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetModelInstances',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.WaitModelReady = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/WaitModelReady',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.GetRecorderStatus = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/GetRecorderStatus',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.FlushRun = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/FlushRun',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.DrainNode = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/DrainNode',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeActionRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.ResumeNode = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/ResumeNode',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeActionRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)
        self.ShutdownController = channel.unary_unary(
                '/ascend_maze.control.v1.LocalControl/ShutdownController',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ShutdownControllerRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
                _registered_method=True)


class LocalControlServicer:
    """Missing associated documentation comment in .proto file."""

    def GetVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetControllerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterSnapshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchCluster(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkerPools(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroyRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskResultHandles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInstances(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitModelReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecorderStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FlushRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShutdownController(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVersion,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetControllerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetControllerStatus,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.GetControllerStatusRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.GetControllerStatusResponse.SerializeToString,
            ),
            'GetSystemSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemSnapshot,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'SubmitWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitWorkflow,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.SubmitWorkflowRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubmission,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetClusterSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterSnapshot,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'WatchCluster': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchCluster,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WatchClusterRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetWorkerPools': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerPools,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'ListRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRuns,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'WatchRun': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRun,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.WatchRunRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetRunEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunEvents,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.GetRunEventsRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'DestroyRun': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroyRun,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetTaskResultHandles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskResultHandles,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetModelCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelCatalog,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetModelInstances': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInstances,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'WaitModelReady': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitModelReady,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'GetRecorderStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecorderStatus,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'FlushRun': grpc.unary_unary_rpc_method_handler(
                    servicer.FlushRun,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'DrainNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainNode,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeActionRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'ResumeNode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeNode,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeActionRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
            'ShutdownController': grpc.unary_unary_rpc_method_handler(
                    servicer.ShutdownController,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ShutdownControllerRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascend_maze.control.v1.LocalControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascend_maze.control.v1.LocalControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocalControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetVersion',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetControllerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetControllerStatus',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.GetControllerStatusRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.GetControllerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetSystemSnapshot',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/SubmitWorkflow',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.SubmitWorkflowRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetSubmission',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetClusterSnapshot',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchCluster(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/WatchCluster',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.WatchClusterRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkerPools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetWorkerPools',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/ListRuns',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetRun',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/WatchRun',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.WatchRunRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetRunEvents',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.GetRunEventsRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/CancelRun',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroyRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/DestroyRun',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskResultHandles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetTaskResultHandles',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetModelCatalog',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInstances(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetModelInstances',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitModelReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/WaitModelReady',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecorderStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/GetRecorderStatus',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlQueryRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FlushRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/FlushRun',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.RunActionRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/DrainNode',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeActionRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/ResumeNode',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.NodeActionRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShutdownController(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.LocalControl/ShutdownController',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ShutdownControllerRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ControlResponseMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ServiceProcessControlStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquirePort = channel.unary_unary(
                '/ascend_maze.control.v1.ServiceProcessControl/AcquirePort',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.AcquireServicePortRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.PortLeaseResponse.FromString,
                _registered_method=True)
        self.ReleasePort = channel.unary_unary(
                '/ascend_maze.control.v1.ServiceProcessControl/ReleasePort',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ReleaseServicePortRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.PortLeaseResponse.FromString,
                _registered_method=True)
        self.Launch = channel.unary_unary(
                '/ascend_maze.control.v1.ServiceProcessControl/Launch',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.LaunchServiceRequestMessage.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceLaunchResponse.FromString,
                _registered_method=True)
        self.Probe = channel.unary_unary(
                '/ascend_maze.control.v1.ServiceProcessControl/Probe',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ProbeServiceRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceProcessProbeMessage.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/ascend_maze.control.v1.ServiceProcessControl/Stop',
                request_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.StopServiceRequest.SerializeToString,
                response_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceStopResultMessage.FromString,
                _registered_method=True)


class ServiceProcessControlServicer:
    """Missing associated documentation comment in .proto file."""

    def AcquirePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleasePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Launch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Probe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceProcessControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquirePort': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquirePort,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.AcquireServicePortRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.PortLeaseResponse.SerializeToString,
            ),
            'ReleasePort': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleasePort,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ReleaseServicePortRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.PortLeaseResponse.SerializeToString,
            ),
            'Launch': grpc.unary_unary_rpc_method_handler(
                    servicer.Launch,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.LaunchServiceRequestMessage.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceLaunchResponse.SerializeToString,
            ),
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ProbeServiceRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceProcessProbeMessage.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.StopServiceRequest.FromString,
                    response_serializer=ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceStopResultMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ascend_maze.control.v1.ServiceProcessControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ascend_maze.control.v1.ServiceProcessControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceProcessControl:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AcquirePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.ServiceProcessControl/AcquirePort',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.AcquireServicePortRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.PortLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleasePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.ServiceProcessControl/ReleasePort',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ReleaseServicePortRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.PortLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Launch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.ServiceProcessControl/Launch',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.LaunchServiceRequestMessage.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceLaunchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.ServiceProcessControl/Probe',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ProbeServiceRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceProcessProbeMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ascend_maze.control.v1.ServiceProcessControl/Stop',
            ascend__maze_dot_control_dot_proto_dot_control__pb2.StopServiceRequest.SerializeToString,
            ascend__maze_dot_control_dot_proto_dot_control__pb2.ServiceStopResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
